- platform: universal
  name: infopuckarna_ha_grupp
  children:
    - media_player.googlehome_vardagsrummet
    - media_player.googlehome_koket
  commands:
    volume_set:
      service: media_player.volume_set
      data_template:
        entity_id:
          - media_player.googlehome_vardagsrummet
          - media_player.googlehome_koket
        volume_level: "{{ volume_level }}"
    volume_mute:
      service: media_player.volume_mute
      data_template:
        entity_id:
          - media_player.googlehome_vardagsrummet
          - media_player.googlehome_koket
        is_volume_muted: "{{ is_volume_muted }}"
    turn_on:
      service: media_player.turn_on
      data_template:
        entity_id:
          - media_player.googlehome_vardagsrummet
          - media_player.googlehome_koket
  attributes:
    state: media_player.googlehome_vardagsrummet
    is_volume_muted: media_player.googlehome_vardagsrummet|is_volume_muted

- platform: universal
  name: alla_puckar_ha_grupp
  children:
    - media_player.googlehome_ilias_rum
    - media_player.googlehome_vardagsrummet
    - media_player.googlehome_sovrummet
    - media_player.googlehome_annas_rum
    - media_player.googlehome_koket
    - media_player.googlehome_eriks_rum
  commands:
    volume_set:
      service: media_player.volume_set
      data_template:
        entity_id:
          - media_player.googlehome_ilias_rum
          - media_player.googlehome_vardagsrummet
          - media_player.googlehome_sovrummet
          - media_player.googlehome_annas_rum
          - media_player.googlehome_koket
          - media_player.googlehome_eriks_rum
        volume_level: "{{ volume_level }}"
    volume_mute:
      service: media_player.volume_mute
      data_template:
        entity_id:
          - media_player.googlehome_ilias_rum
          - media_player.googlehome_vardagsrummet
          - media_player.googlehome_sovrummet
          - media_player.googlehome_annas_rum
          - media_player.googlehome_koket
          - media_player.googlehome_eriks_rum
        is_volume_muted: "{{ is_volume_muted }}"
    turn_on:
      service: media_player.turn_on
      data_template:
        entity_id:
          - media_player.googlehome_ilias_rum
          - media_player.googlehome_vardagsrummet
          - media_player.googlehome_sovrummet
          - media_player.googlehome_annas_rum
          - media_player.googlehome_koket
          - media_player.googlehome_eriks_rum
  attributes:
    state: media_player.googlehome_ilias_rum
    is_volume_muted: media_player.googlehome_ilias_rum|is_volume_muted

- platform: universal
  name: alla_hogtalare_ha_grupp
  children:
    - media_player.googlehome_ilias_rum
    - media_player.googlehome_vardagsrummet
    - media_player.googlehome_sovrummet
    - media_player.googlehome_annas_rum
    - media_player.googlehome_koket
    - media_player.googlehome_eriks_rum
    - media_player.stereon_i_vardagsrummet
    - media_player.annas_stereo
    - media_player.hogtalarna_i_koket
    - media_player.eriks_stereo
  commands:
    volume_set:
      service: media_player.volume_set
      data_template:
        entity_id:
          - media_player.googlehome_ilias_rum
          - media_player.googlehome_vardagsrummet
          - media_player.googlehome_sovrummet
          - media_player.googlehome_annas_rum
          - media_player.googlehome_koket
          - media_player.googlehome_eriks_rum
          - media_player.stereon_i_vardagsrummet
          - media_player.annas_stereo
          - media_player.hogtalarna_i_koket
          - media_player.eriks_stereo
        volume_level: "{{ volume_level }}"
    volume_mute:
      service: media_player.volume_mute
      data_template:
        entity_id:
          - media_player.googlehome_ilias_rum
          - media_player.googlehome_vardagsrummet
          - media_player.googlehome_sovrummet
          - media_player.googlehome_annas_rum
          - media_player.googlehome_koket
          - media_player.googlehome_eriks_rum
          - media_player.stereon_i_vardagsrummet
          - media_player.annas_stereo
          - media_player.hogtalarna_i_koket
          - media_player.eriks_stereo
        is_volume_muted: "{{ is_volume_muted }}"
    turn_on:
      service: media_player.turn_on
      data_template:
        entity_id:
          - media_player.googlehome_ilias_rum
          - media_player.googlehome_vardagsrummet
          - media_player.googlehome_sovrummet
          - media_player.googlehome_annas_rum
          - media_player.googlehome_koket
          - media_player.googlehome_eriks_rum
          - media_player.stereon_i_vardagsrummet
          - media_player.annas_stereo
          - media_player.hogtalarna_i_koket
          - media_player.eriks_stereo
  attributes:
    state: media_player.googlehome_ilias_rum
    is_volume_muted: media_player.googlehome_ilias_rum|is_volume_muted

- platform: universal
  name: de_besta_hogtalarna_ha_grupp
  children:
    - media_player.stereon_i_vardagsrummet
    - media_player.annas_stereo
    - media_player.hogtalarna_i_koket
    - media_player.eriks_stereo
  commands:
    volume_set:
      service: media_player.volume_set
      data_template:
        entity_id:
          - media_player.stereon_i_vardagsrummet
          - media_player.annas_stereo
          - media_player.hogtalarna_i_koket
          - media_player.eriks_stereo
        volume_level: "{{ volume_level }}"
    volume_mute:
      service: media_player.volume_mute
      data_template:
        entity_id:
          - media_player.stereon_i_vardagsrummet
          - media_player.annas_stereo
          - media_player.hogtalarna_i_koket
          - media_player.eriks_stereo
        is_volume_muted: "{{ is_volume_muted }}"
    turn_on:
      service: media_player.turn_on
      data_template:
        entity_id:
          - media_player.stereon_i_vardagsrummet
          - media_player.annas_stereo
          - media_player.hogtalarna_i_koket
          - media_player.eriks_stereo
  attributes:
    state: media_player.stereon_i_vardagsrummet
    is_volume_muted: media_player.stereon_i_vardagsrummet|is_volume_muted
